name: Linux x86_64

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: unit tests
      run: |
        cargo test --all --release

    - name: upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64-ubuntu-20.04
        path: target/release/busser


  build_test_with_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y && cargo install cargo-tarpaulin

    - name: unit tests
      run: |
        cargo build --release && cargo tarpaulin --out json

    - name: upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64-lastest
        path: target/release/busser

    - name: upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: tarpaulin-report.json