name: Build and test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: unit tests
      run: |
        cargo test --all --release

    - name: upload bundle
      if: ${{ startsWith(matrix.os, 'ubuntu-20.04') }}
      uses: actions/upload-artifact@v4
      with:
        name: busser
        path: target/release/busser
